export interface NumberTraits {
  color: string;
  label: { EN: string; HI: string };
  single: { EN: string[]; HI: string[] };
  multiple: { EN: string[]; HI: string[] };
  multipleCondition: (count: number) => boolean;
}

export const NUMBER_TRAITS: Record<number, NumberTraits> = {
  1: {
    color: "#ef4444",
    label: { EN: "Number 1", HI: "अंक 1" },
    single: {
      EN: [
        "Confident",
        "Leadership Quality",
        "Name & Fame",
        "Stubborn",
        "Dominating",
        "Strong Ego",
        "Short-Tempered",
        "Powerful & Wealthy",
        "Desire to Know & Speak",
      ],
      HI: [
        "आत्मविश्वासी",
        "नेतृत्व गुण",
        "नाम और शोहरत",
        "जिद्दी",
        "प्रभावशाली",
        "तेज अहंकार",
        "जल्दी गुस्सा",
        "शक्तिशाली और धनवान",
        "जानने की तीव्र इच्छा",
      ],
    },
    multiple: {
      EN: [
        "Over-Dominating",
        "Highly Egoistic",
        "Reduced Earning Potential",
        "Insecure Nature",
        "Lack of Confidence",
        "Highly Compliant",
      ],
      HI: [
        "अति प्रभावशाली",
        "अत्यधिक अहंकारी",
        "कम आय संभावना",
        "असुरक्षित स्वभाव",
        "आत्मविश्वास की कमी",
        "अत्यधिक अनुपालन",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  2: {
    color: "#f97316",
    label: { EN: "Number 2", HI: "अंक 2" },
    single: {
      EN: [
        "Motherly Nature",
        "Emotional",
        "Creative",
        "Soft-Spoken",
        "Needs Emotional Support",
        "Needs Pampering",
        "Needs Motivation",
        "Loves Selfies",
        "Photogenic",
      ],
      HI: [
        "मातृस्वभाव",
        "भावनात्मक",
        "रचनात्मक",
        "मृदुभाषी",
        "भावनात्मक समर्थन की आवश्यकता",
        "लाड़-प्यार की आवश्यकता",
        "प्रेरणा की आवश्यकता",
        "सेल्फी प्रिय",
        "फोटोजेनिक",
      ],
    },
    multiple: {
      EN: [
        "Over-Emotional",
        "Over-Creative",
        "Over-Soft-Spoken",
        "Needs More Motivation & Support",
        "Needs More Pampering",
        "Co-Dependent",
        "Possessive",
        "Cannot Keep Secrets",
        "Very Talkative",
        "Needs Partner's Attention",
      ],
      HI: [
        "अति भावनात्मक",
        "अति रचनात्मक",
        "अति मृदुभाषी",
        "अधिक समर्थन की आवश्यकता",
        "अत्यधिक लाड़",
        "परनिर्भर",
        "अधिकारी स्वभाव",
        "राज़ नहीं रख सकते",
        "बहुत बातूनी",
        "साथी का ध्यान ज़रूरी",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  3: {
    color: "#eab308",
    label: { EN: "Number 3", HI: "अंक 3" },
    single: {
      EN: [
        "Good Planner",
        "Good Decision Maker",
        "Hunger for Knowledge",
        "Resists Temptations",
        "Disciplined",
        "Good Counselor",
        "Clear Priorities",
        "Justice-Oriented Life",
        "Good Stress Management",
        "Family First",
        "Wise",
        "Consults Family Before Deciding",
      ],
      HI: [
        "अच्छे योजनाकार",
        "अच्छे निर्णयकर्ता",
        "ज्ञान की भूख",
        "प्रलोभन से दूर",
        "अनुशासित",
        "अच्छे सलाहकार",
        "प्राथमिकताएं स्पष्ट",
        "न्याय-आधारित जीवन",
        "तनाव प्रबंधन",
        "परिवार प्राथमिकता",
        "बुद्धिमान",
        "परिवार से परामर्श",
      ],
    },
    multiple: {
      EN: [
        "Shows Off Knowledge & Wisdom",
        "Pretends to Care for Family",
        "Selfish Thinker",
        "Opportunistic",
        "Easily Cheats for Profit",
        "Storyteller",
        "Manipulative",
        "Good at Sales",
      ],
      HI: [
        "ज्ञान का दिखावा",
        "परिवार की परवाह का नाटक",
        "स्वार्थी सोच",
        "अवसरवादी",
        "लाभ के लिए धोखा",
        "कहानीकार",
        "चालाकी से प्रभावित",
        "बिक्री में माहिर",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  4: {
    color: "#22c55e",
    label: { EN: "Number 4", HI: "अंक 4" },
    single: {
      EN: [
        "Mood Swings",
        "Sudden Life Problems",
        "Unstable Relationships",
        "Fruitless Expensive Travels",
        "Irregular Plans",
        "Poor Life Planning",
        "Unrealistic Goals",
        "Health Hazards & Accidents",
        "Party Lover",
        "Spendthrift",
        "Large But Unmaintained Social Circle",
        "IT / Research Depth",
      ],
      HI: [
        "मूड स्विंग्स",
        "अचानक जीवन समस्याएं",
        "अस्थिर रिश्ते",
        "व्यर्थ महंगी यात्राएं",
        "अनियमित योजनाएं",
        "जीवन नियोजन कमज़ोर",
        "अवास्तविक लक्ष्य",
        "स्वास्थ्य खतरे",
        "पार्टी प्रिय",
        "फिज़ूलखर्ची",
        "बड़ा पर अस्थिर सामाजिक दायरा",
        "आईटी / गहन शोध",
      ],
    },
    multiple: {
      EN: [
        "Reduced Negative Qualities",
        "Fruitful Planner",
        "Fruitful Travels",
        "Stable Relationships",
        "Good Planner",
        "Predictable & Reliable",
      ],
      HI: [
        "नकारात्मकता कम",
        "फलदायी योजनाकार",
        "फलदायी यात्राएं",
        "स्थिर रिश्ते",
        "अच्छे योजनाकार",
        "विश्वसनीय",
      ],
    },
    multipleCondition: (c) => c % 2 === 0,
  },
  5: {
    color: "#14b8a6",
    label: { EN: "Number 5", HI: "अंक 5" },
    single: {
      EN: [
        "Calculative Mind (Money-Focused)",
        "Good Speaker",
        "Excellent Negotiator",
        "Highly Money-Making Ideas",
        "Highly Routinized",
        "Straightforward",
        "Routine Follower",
      ],
      HI: [
        "पैसे के मामले में गणनात्मक",
        "अच्छे वक्ता",
        "उत्कृष्ट वार्ताकार",
        "धन कमाने के विचार",
        "दिनचर्या का पालन",
        "सीधे-साफ",
        "नियमित",
      ],
    },
    multiple: {
      EN: [
        "Anxiety from Birth",
        "Fast Brain",
        "Sleep Problems",
        "High Chances of Fraud (Victim or Perpetrator)",
        "Over-Thinking",
      ],
      HI: [
        "जन्मजात चिंता",
        "तेज़ दिमाग",
        "नींद की समस्या",
        "धोखाधड़ी की अधिक संभावना",
        "अति-विचार",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  6: {
    color: "#3b82f6",
    label: { EN: "Number 6", HI: "अंक 6" },
    single: {
      EN: [
        "Loves Good Food",
        "Cooking Aptitude",
        "Comfort First",
        "Large Friend Circle (Opposite Gender)",
        "Loves Materialistic Things",
        "Drawn to Outer Beauty",
        "Presentation-Focused",
        "Creative (Models, Fashion, Art)",
        "Attractive Aura",
        "Foodie",
      ],
      HI: [
        "अच्छे खाने का शौक",
        "खाना बनाने की क्षमता",
        "आराम प्राथमिकता",
        "बड़ा मित्र मंडल",
        "भौतिक चीज़ें पसंद",
        "बाहरी सौंदर्य आकर्षण",
        "प्रस्तुति पर ध्यान",
        "रचनात्मक",
        "आकर्षक व्यक्तित्व",
        "खाने के शौकीन",
      ],
    },
    multiple: {
      EN: [
        "Conflicts with Women",
        "Attracted to Different Genders",
        "Uses Harsh Words",
        "Fighter",
        "Less Attractive",
        "Less Creative",
        "Average Cooking Skills",
      ],
      HI: [
        "महिलाओं से झगड़े",
        "विभिन्न लिंगों की ओर आकर्षण",
        "कठोर शब्दों का प्रयोग",
        "लड़ाकू स्वभाव",
        "कम आकर्षक",
        "कम रचनात्मक",
        "साधारण खाना पकाने का कौशल",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  7: {
    color: "#6366f1",
    label: { EN: "Number 7", HI: "अंक 7" },
    single: {
      EN: [
        "Lucky",
        "Clear Vision of Goals",
        "Planned & Fruitful Travel",
        "Easy Visa to Developed Countries",
        "Stable Long-Term Relationships",
        "Good Reasoning",
        "Logic-Driven",
        "Researcher",
      ],
      HI: [
        "भाग्यशाली",
        "लक्ष्य की स्पष्ट दृष्टि",
        "फलदायी यात्राएं",
        "विकसित देशों का वीज़ा सुलभ",
        "स्थिर रिश्ते",
        "तर्कशील",
        "तर्क-प्रेरित",
        "शोधकर्ता",
      ],
    },
    multiple: {
      EN: [
        "Unstable Life",
        "Less Fruitful Travel",
        "Low PR/Foreign Settlement Chances",
        "Anxious Nature",
        "Meaningless Conversations",
        "Over-Questioning",
        "Depth Seeker",
      ],
      HI: [
        "अस्थिर जीवन",
        "कम फलदायी यात्राएं",
        "विदेश बसने की कम संभावना",
        "चिंतित स्वभाव",
        "अर्थहीन बातें",
        "अधिक प्रश्न करना",
        "गहराई खोजने वाले",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
  8: {
    color: "#a855f7",
    label: { EN: "Number 8", HI: "अंक 8" },
    single: {
      EN: [
        "God Believer",
        "Prone to Depression (When Idle)",
        "Substance Risk",
        "Attractive Aura",
        "Life Struggles",
        "Disappointments",
        "Extreme Life Events",
        "Hard Worker",
        "Helpful",
        "Empathetic",
        "Delayed Results",
        "Fights for Justice",
        "Seeks Revenge When Hurt",
      ],
      HI: [
        "ईश्वर में विश्वास",
        "आलस्य में अवसाद की संभावना",
        "नशे का जोख़िम",
        "आकर्षक व्यक्तित्व",
        "जीवन संघर्ष",
        "निराशाएं",
        "जीवन में चरम घटनाएं",
        "कठोर परिश्रमी",
        "सहायक",
        "सहानुभूतिशील",
        "देरी से परिणाम",
        "न्याय के लिए लड़ते हैं",
        "ठेस लगने पर बदला",
      ],
    },
    multiple: {
      EN: [
        "Good for Making Money",
        "Asset Building",
        "Management Skills",
        "God Believer",
        "Less Struggle",
        "Attractive Aura",
        "Sympathetic",
        "Family-Oriented",
        "Truth Seeker",
      ],
      HI: [
        "पैसे के लिए अच्छा",
        "संपत्ति निर्माण",
        "प्रबंधन कुशल",
        "ईश्वर में विश्वास",
        "कम संघर्ष",
        "आकर्षक व्यक्तित्व",
        "सहानुभूतिशील",
        "परिवार-उन्मुख",
        "सत्य प्रेमी",
      ],
    },
    multipleCondition: (c) => c % 2 === 0,
  },
  9: {
    color: "#ec4899",
    label: { EN: "Number 9", HI: "अंक 9" },
    single: {
      EN: [
        "Aggressive",
        "Bold",
        "Energetic",
        "Physical Activity Lover",
        "Courageous",
        "Determined",
        "Confident",
        "Argumentative",
        "Short-Tempered",
      ],
      HI: [
        "आक्रामक",
        "साहसी",
        "ऊर्जावान",
        "शारीरिक गतिविधि प्रिय",
        "निड़र",
        "दृढ़",
        "आत्मविश्वासी",
        "तर्कप्रिय",
        "जल्दी गुस्सा",
      ],
    },
    multiple: {
      EN: [
        "Less Courage",
        "Less Aggression",
        "Uncontrolled Anger When Triggered",
        "Frustrated",
        "Uses Harsh Words in Anger",
      ],
      HI: [
        "कम साहस",
        "कम आक्रामकता",
        "क्रोध पर नियंत्रण नहीं",
        "निराश",
        "क्रोध में कठोर भाषा",
      ],
    },
    multipleCondition: (c) => c > 1,
  },
};
