/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: string;
    title: string;
    content: string;
    published: boolean;
    createdAt: Timestamp;
    author: string;
}
export interface UserProfile {
    id: Principal;
    name: string;
    createdAt: Timestamp;
    email: string;
}
export type Timestamp = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: bigint;
    name: string;
    price: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Notice {
    id: string;
    title: string;
    active: boolean;
    createdAt: Timestamp;
    message: string;
}
export interface Inquiry {
    id: string;
    dob?: string;
    tob?: string;
    palmPhotos: Array<ExternalBlob | null>;
    question: string;
    authorId?: Principal;
    seedNumber?: bigint;
    city?: string;
    submittedAt: Timestamp;
    birthCountry?: string;
    handPicture?: ExternalBlob;
    state?: string;
    visitorName: string;
    pastLifeNotes: string;
    serviceId: bigint;
    relationshipPerson2?: Person;
}
export interface NumerologyUser {
    username: string;
    passwordHash: string;
    sectionLevel: bigint;
}
export interface Person {
    dob?: string;
    tob?: string;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface VisitorID {
    service: string;
    expiresAt: Timestamp;
    username: string;
    password: string;
    createdAt: Timestamp;
    visitorName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(title: string, content: string, author: string): Promise<string>;
    deleteInquiry(id: string): Promise<void>;
    deletePost(id: string): Promise<void>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllPosts(): Promise<Array<BlogPost>>;
    getAllPostsAdmin(): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getServices(): Promise<Array<Service>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    noticeCreate(adminEmail: string, adminPassword: string, title: string, message: string): Promise<string>;
    noticeDelete(adminEmail: string, adminPassword: string, id: string): Promise<void>;
    noticeList(): Promise<Array<Notice>>;
    noticeListAll(adminEmail: string, adminPassword: string): Promise<Array<Notice>>;
    noticeToggleActive(adminEmail: string, adminPassword: string, id: string): Promise<void>;
    numerologyCreateUser(adminUsername: string, adminPassword: string, username: string, password: string, sectionLevel: bigint): Promise<void>;
    numerologyDeleteUser(adminUsername: string, adminPassword: string, username: string): Promise<void>;
    numerologyListUsers(adminUsername: string, adminPassword: string): Promise<Array<NumerologyUser>>;
    numerologyLogin(username: string, password: string): Promise<bigint>;
    publishPost(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInquiry(inquiry: Inquiry): Promise<string>;
    updatePost(id: string, title: string, content: string, author: string): Promise<void>;
    visitorCreateId(adminEmail: string, adminPassword: string, service: string, visitorName: string, username: string, password: string, expiryDays: bigint): Promise<void>;
    visitorDeleteId(adminEmail: string, adminPassword: string, username: string): Promise<void>;
    visitorListIds(adminEmail: string, adminPassword: string): Promise<Array<VisitorID>>;
    visitorLoginByEmail(email: string, password: string): Promise<{service: string; visitorName: string} | null>;
    adminCreateVisitorId(adminEmail: string, adminPassword: string, service: string, visitorName: string, username: string, password: string, expiryDays: bigint): Promise<void>;
    adminListVisitorIds(adminEmail: string, adminPassword: string): Promise<Array<VisitorID>>;
    adminDeleteVisitorId(adminEmail: string, adminPassword: string, username: string): Promise<void>;
    visitorValidateId(service: string, username: string, password: string): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, Inquiry as _Inquiry, Person as _Person, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteInquiry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostsAdmin();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async noticeCreate(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.noticeCreate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noticeCreate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async noticeDelete(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.noticeDelete(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noticeDelete(arg0, arg1, arg2);
            return result;
        }
    }
    async noticeList(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.noticeList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noticeList();
            return result;
        }
    }
    async noticeListAll(arg0: string, arg1: string): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.noticeListAll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noticeListAll(arg0, arg1);
            return result;
        }
    }
    async noticeToggleActive(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.noticeToggleActive(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noticeToggleActive(arg0, arg1, arg2);
            return result;
        }
    }
    async numerologyCreateUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.numerologyCreateUser(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.numerologyCreateUser(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async numerologyDeleteUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.numerologyDeleteUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.numerologyDeleteUser(arg0, arg1, arg2);
            return result;
        }
    }
    async numerologyListUsers(arg0: string, arg1: string): Promise<Array<NumerologyUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.numerologyListUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.numerologyListUsers(arg0, arg1);
            return result;
        }
    }
    async numerologyLogin(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.numerologyLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.numerologyLogin(arg0, arg1);
            return result;
        }
    }
    async publishPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishPost(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: Inquiry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(await to_candid_Inquiry_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(await to_candid_Inquiry_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePost(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async visitorCreateId(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.visitorCreateId(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visitorCreateId(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async visitorDeleteId(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.visitorDeleteId(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visitorDeleteId(arg0, arg1, arg2);
            return result;
        }
    }
    async visitorListIds(arg0: string, arg1: string): Promise<Array<VisitorID>> {
        if (this.processError) {
            try {
                const result = await this.actor.visitorListIds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visitorListIds(arg0, arg1);
            return result;
        }
    }
    async visitorLoginByEmail(arg0: string, arg1: string): Promise<{service: string; visitorName: string} | null> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).visitorLoginByEmail(arg0, arg1);
                if (result === null || result === undefined) return null;
                if (Array.isArray(result) && result.length === 0) return null;
                const r = Array.isArray(result) ? result[0] : result;
                return r ? { service: r.service, visitorName: r.visitorName } : null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).visitorLoginByEmail(arg0, arg1);
            if (result === null || result === undefined) return null;
            if (Array.isArray(result) && result.length === 0) return null;
            const r = Array.isArray(result) ? result[0] : result;
            return r ? { service: r.service, visitorName: r.visitorName } : null;
        }
    }
    async visitorValidateId(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.visitorValidateId(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visitorValidateId(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreateVisitorId(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                await (this.actor as any).adminCreateVisitorId(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await (this.actor as any).adminCreateVisitorId(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }
    }
    async adminListVisitorIds(arg0: string, arg1: string): Promise<Array<VisitorID>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).adminListVisitorIds(arg0, arg1);
                return Array.isArray(result) ? result : [];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).adminListVisitorIds(arg0, arg1);
            return Array.isArray(result) ? result : [];
        }
    }
    async adminDeleteVisitorId(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                await (this.actor as any).adminDeleteVisitorId(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await (this.actor as any).adminDeleteVisitorId(arg0, arg1, arg2);
        }
    }

}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Inquiry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Promise<Inquiry> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Person_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Person {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Person]): Person | null {
    return value.length === 0 ? null : from_candid_Person_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: [] | [string];
    tob: [] | [string];
    palmPhotos: Array<[] | [_ExternalBlob]>;
    question: string;
    authorId: [] | [Principal];
    seedNumber: [] | [bigint];
    city: [] | [string];
    submittedAt: _Timestamp;
    birthCountry: [] | [string];
    handPicture: [] | [_ExternalBlob];
    state: [] | [string];
    visitorName: string;
    pastLifeNotes: string;
    serviceId: bigint;
    relationshipPerson2: [] | [_Person];
}): Promise<{
    id: string;
    dob?: string;
    tob?: string;
    palmPhotos: Array<ExternalBlob | null>;
    question: string;
    authorId?: Principal;
    seedNumber?: bigint;
    city?: string;
    submittedAt: Timestamp;
    birthCountry?: string;
    handPicture?: ExternalBlob;
    state?: string;
    visitorName: string;
    pastLifeNotes: string;
    serviceId: bigint;
    relationshipPerson2?: Person;
}> {
    return {
        id: value.id,
        dob: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.dob)),
        tob: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.tob)),
        palmPhotos: await from_candid_vec_n14(_uploadFile, _downloadFile, value.palmPhotos),
        question: value.question,
        authorId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.authorId)),
        seedNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.seedNumber)),
        city: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.city)),
        submittedAt: value.submittedAt,
        birthCountry: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.birthCountry)),
        handPicture: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.handPicture)),
        state: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.state)),
        visitorName: value.visitorName,
        pastLifeNotes: value.pastLifeNotes,
        serviceId: value.serviceId,
        relationshipPerson2: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.relationshipPerson2))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: [] | [string];
    tob: [] | [string];
    name: string;
}): {
    dob?: string;
    tob?: string;
    name: string;
} {
    return {
        dob: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.dob)),
        tob: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.tob)),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Promise<Array<Inquiry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Inquiry_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_ExternalBlob]>): Promise<Array<ExternalBlob | null>> {
    return await Promise.all(value.map(async (x)=>await from_candid_opt_n15(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Inquiry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Inquiry): Promise<_Inquiry> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Person_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Person): _Person {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob?: string;
    tob?: string;
    palmPhotos: Array<ExternalBlob | null>;
    question: string;
    authorId?: Principal;
    seedNumber?: bigint;
    city?: string;
    submittedAt: Timestamp;
    birthCountry?: string;
    handPicture?: ExternalBlob;
    state?: string;
    visitorName: string;
    pastLifeNotes: string;
    serviceId: bigint;
    relationshipPerson2?: Person;
}): Promise<{
    id: string;
    dob: [] | [string];
    tob: [] | [string];
    palmPhotos: Array<[] | [_ExternalBlob]>;
    question: string;
    authorId: [] | [Principal];
    seedNumber: [] | [bigint];
    city: [] | [string];
    submittedAt: _Timestamp;
    birthCountry: [] | [string];
    handPicture: [] | [_ExternalBlob];
    state: [] | [string];
    visitorName: string;
    pastLifeNotes: string;
    serviceId: bigint;
    relationshipPerson2: [] | [_Person];
}> {
    return {
        id: value.id,
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        tob: value.tob ? candid_some(value.tob) : candid_none(),
        palmPhotos: await to_candid_vec_n26(_uploadFile, _downloadFile, value.palmPhotos),
        question: value.question,
        authorId: value.authorId ? candid_some(value.authorId) : candid_none(),
        seedNumber: value.seedNumber ? candid_some(value.seedNumber) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        submittedAt: value.submittedAt,
        birthCountry: value.birthCountry ? candid_some(value.birthCountry) : candid_none(),
        handPicture: value.handPicture ? candid_some(await to_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.handPicture)) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        visitorName: value.visitorName,
        pastLifeNotes: value.pastLifeNotes,
        serviceId: value.serviceId,
        relationshipPerson2: value.relationshipPerson2 ? candid_some(to_candid_Person_n29(_uploadFile, _downloadFile, value.relationshipPerson2)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob?: string;
    tob?: string;
    name: string;
}): {
    dob: [] | [string];
    tob: [] | [string];
    name: string;
} {
    return {
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        tob: value.tob ? candid_some(value.tob) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob | null>): Promise<Array<[] | [_ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await to_candid_opt_n27(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
